### ISSUE TITLE
Accessing InApp Browser from mobile site

### ISSUE THREAD

**Issue by minhal** [adobe-marketing-cloud-mobile/aemm-plugin-inappbrowser#1]
I have a mobile site that i am displaying through phonegap container and i need to display an in app browser for some of the links on the mobile site. Is it possible to use this plugin on mobile-sites.

**Comment by adzellman** [comment]
Hi @minhal, unfortunately this plugin will not work in that case. This plugin was built specifically to work with AEM Mobile applications. It is exposing an API that exists in AEM Mobile to create in-app browsers through a Cordova API. The Cordova layer is not actually generating the in-app browser.
